# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('posts', '0002_auto_20160802_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_title', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=100)),
                ('avatar', models.FileField(upload_to='')),
            ],
        ),
    ]
