# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20160803_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_comments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
