# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160803_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
