# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
