# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20160804_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_likes',
        ),
    ]
