# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('auth', '0008_alter_user_username_max_length'),
        ('posts', '0016_auto_20160806_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('wiwiker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to='')),
            ],
        ),
    ]
