# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
