# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20160807_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
