# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20160813_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
