# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20160813_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hats', to='posts.Categories'),
        ),
    ]
