# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_auto_20160904_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.CharField(max_length=10000),
        ),
    ]
