# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20160904_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.TextField(max_length=10000),
        ),
    ]
