# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_remove_post_has_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='static/placeholder.jpg', upload_to=''),
        ),
    ]
