# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20160815_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default=0, upload_to=''),
        ),
    ]
