# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20160816_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
