# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20160816_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
