# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_auto_20160905_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default='static/placeholder.jpg', upload_to=''),
        ),
    ]
